/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_rn_native_OpenNativeModule */

#ifndef _Included_com_test_rn_native_OpenNativeModule
#define _Included_com_test_rn_native_OpenNativeModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_rn_native_OpenNativeModule
 * Method:    testParams
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_1rn_1native_OpenNativeModule_testParams
  (JNIEnv *, jobject, jobjectArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
